### PR TITLE
added publisher for m100 velodyne points for melodic

### PR DESCRIPTION
**Pull request by preetijain7681**

### CODE REVIEW

**Comment by MihirDharmadhikari** [comment]
Hello, 
Thank you very much this PR. Can you please change the ```/m100/velodyne_points``` to ```/$(arg robot_name)/velodyne_points```. This will make sure that the namespace in which the robot is launched is same as that of the pointlcoud topic subscribed by gbplanner_node.

**Comment by preetijain7681** [comment]
Yes sure.

**Comment by MihirDharmadhikari** [comment]
I went ahead and made this change as it was pending for quite some time.

**Comment by preetijain7681** [comment]
Thank you.

**Pull request closed without merging**
